name: Python project check

on:
  push:
    branches:
      - news

jobs:
  build:
    runs-on: windows

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check style
      run: |
        pip install pycodestyle
        pycodestyle .

    - name: Build project
      run: |
        python main.py build